name: TrainSignals
depend:
  - Train_Carts
  - BKCommonLib
version: ${project.version}
main: nl.ijsglijder.traincraft.TrainCraft
api-version: 1.15
description: Rail signals for mc!
author: ijsglijder

commands:
  signal:
    description: Signal command
permissions:
  trainsignals.use:
    default: op
    description: Basic perm
    children: {}